name: audio_service_example
description: Demonstrates how to use the audio_service plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1
  audio_session: ^0.1.7
  just_audio: ^0.9.24
  flutter_tts: ^3.3.3
  device_info_plus: ^3.2.1
  android_content_provider: ^0.2.0
  permission_handler: ^8.3.0
  rxdart: ^0.27.2
  audio_service:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true