name: audio_service_platform_interface
description: A common platform interface for the audio_service plugin. Different platform implementations of audio_service should implement this interface.
homepage: https://github.com/ryanheise/audio_service/tree/master/audio_service_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

  # Use these deps for local development
  # audio_service_platform_interface_entities:
  #   path: ../audio_service_platform_interface_entities

  # Use these deps when pushing to origin (for the benefit of testers)
  audio_service_platform_interface_entities:
    git:
      url: https://github.com/ryanheise/audio_service.git
      ref: one-isolate
      path: audio_service_platform_interface_entities

  # Use these deps when publishing.
  # audio_service_platform_interface_entities: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  pedantic: ^1.10.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"
