name: audio_service_platform_interface_entities
description: Data classes for audio_service_platform_interface.
version: 0.1.0
homepage: https://github.com/ryanheise/audio_service/tree/master/audio_service_platform_interface_entities

environment:
  sdk: '>=2.12.0 <3.0.0'
